{% set name = "beakerx-kernel-scala" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/twosigma/beakerx_kernel_scala.git
  git_tag: master

source:
  url: https://files.pythonhosted.org/packages/source/b/beakerx/{{ name }}-{{ version }}.tar.gz
  #url: file:///YOUR_LOCAL_PATH/beakerx_kernel_scala/scala-dist/dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 1
  script: pip install --no-deps .
  entry_points:
  - beakerx-kernel-scala = beakerx:run

requirements:
  build:
  - python
  - pip
  run:
  - python >=3
  - notebook >=5.7.4
  - ipywidgets >=7.0
  - widgetsnbextension
  - openjdk=11.0.1